; ==================================================
; SETTINGS SKINS

[PageActive]
StringAlign=RightCenter
FontFace=Merienda
FontColor=255,255,255
FontSize=18
SolidColor=0,0,0,1
AntiAlias=1

[SettingActive]
StringAlign=RightCenter
FontFace=Merienda
FontColor=255,255,255
FontSize=18
SolidColor=0,0,0,1
AntiAlias=1

; ==================================================
; PAGE INFO

[InfoTitle]
StringAlign=LeftCenter
FontFace=Merienda
FontSize=32
FontColor=255,215,0
AntiAlias=1

[InfoVersion]
StringAlign=LeftCenter
FontFace=TT Squares Condensed
FontSize=16
FontColor=255,255,255
AntiAlias=1

[InfoAuthor]
StringAlign=LeftCenter
FontFace=TT Squares Condensed
FontSize=14
FontColor=255,255,255
AntiAlias=1

[InfoHeader]
StringAlign=LeftCenter
FontFace=Merienda
FontSize=18
FontColor=255,215,0
AntiAlias=1

[InfoLicense]
StringAlign=LeftCenter
FontFace=TT Squares Condensed
FontSize=12
FontColor=255,255,255
AntiAlias=1

[InfoActive]
StringAlign=LeftCenter
FontFace=TT Squares Condensed
FontColor=255,255,255
FontSize=12
SolidColor=0,0,0,1
AntiAlias=1

; ==================================================
; PAGE SKINS

[SkinText]
StringAlign=CenterCenter
FontFace=Merienda
FontSize=24
FontColor=255,255,255
AntiAlias=1

[SkinInfo]
StringAlign=LeftCenter
FontFace=TT Squares Condensed
FontSize=18
FontColor=255,255,255
AntiAlias=1

[SkinArrow]
StringAlign=CenterCenter
FontFace=TT Squares Condensed
FontSize=18
FontColor=255,255,255
AntiAlias=1

[SkinTypefaceActive]
StringAlign=CenterCenter
FontFace=TT Squares Condensed
FontSize=14
FontColor=255,255,255
SolidColor=0,0,0,1
AntiAlias=1

[SkinActive]
StringAlign=CenterCenter
FontFace=TT Squares Condensed
FontSize=18
FontColor=255,255,255
SolidColor=0,0,0,1
AntiAlias=1

; ==================================================
; PAGE WEATHER

[WeatherText]
StringAlign=CenterCenter
FontFace=Merienda
FontSize=24
FontColor=255,255,255
AntiAlias=1

[WeatherInfo]
StringAlign=CenterCenter
FontFace=TT Squares Condensed
FontSize=18
FontColor=255,255,255
AntiAlias=1

[WeatherNote]
StringAlign=CenterCenter
FontFace=TT Squares Condensed
FontSize=16
FontColor=255,255,255
AntiAlias=1

[WeatherArrow]
StringAlign=CenterCenter
FontFace=TT Squares Condensed
FontSize=18
FontColor=255,255,255
AntiAlias=1

[WeatherActive]
StringAlign=CenterCenter
FontFace=TT Squares Condensed
FontSize=18
FontColor=255,255,255
SolidColor=0,0,0,1
AntiAlias=1

; ==================================================
; PAGE LANGUAGE

[LanguageText]
StringAlign=CenterCenter
FontFace=TT Squares Condensed
FontSize=18
FontColor=255,255,255
AntiAlias=1

[LanguageCurrent]
StringAlign=CenterCenter
FontFace=Merienda
FontSize=24
FontColor=255,215,0
AntiAlias=1

[LanguageInfo]
StringAlign=CenterCenter
FontFace=TT Squares Condensed
FontSize=18
FontColor=255,255,255
AntiAlias=1

[LanguageActive]
StringAlign=CenterCenter
FontFace=TT Squares Condensed
FontSize=18
FontColor=255,255,255
SolidColor=0,0,0,1
AntiAlias=1

; ==================================================
; CLOCK SKINS

[ClockDate]
StringAlign=LeftCenter
FontFace=#TypeFace#
FontColor=#ColorCode#
FontSize=(20*#SuiteScale#)
AntiAlias=1
DynamicVariables=1

[ClockTime]
StringAlign=LeftCenter
StringCase=Lower
FontFace=#TypeFace#
FontColor=#ColorCode#
FontSize=(75*#SuiteScale#)
FontWeight=700
AntiAlias=1
DynamicVariables=1

[ClockDateCh]
StringAlign=LeftCenter
FontFace=#TypeFace#
FontColor=[DesktopFG2]FF
FontSize=(20*#SuiteScale#)
AntiAlias=1
DynamicVariables=1

[ClockTimeCh]
StringAlign=LeftCenter
StringCase=Lower
FontFace=#TypeFace#
FontColor=[DesktopFG1]FF
FontSize=(75*#SuiteScale#)
FontWeight=700
AntiAlias=1
DynamicVariables=1

; ==================================================
; SPOTIFY SKINS

[SpotifyStyleRetreieve]
StringAlign=CenterCenter
FontFace=#TypeFace#
FontColor=#ColorCode#
FontSize=(30*#SuiteScale#)
AntiAlias=1
DynamicVariables=1

[SpotifyStyleTitle]
StringAlign=LeftCenter
StringCase=None
StringStyle=Normal
FontColor=#ColorCode#
FontFace=#TypeFace#
FontSize=(15*#SuiteScale#)
AntiAlias=1
ClipString=1
DynamicVariables=1

[SpotifyStyleArtist]
StringAlign=LeftCenter
StringCase=None
StringStyle=Normal
FontColor=#ColorCode#
FontFace=#TypeFace#
FontSize=(15*#SuiteScale#)
AntiAlias=1
ClipString=1
DynamicVariables=1

[SpotifyStyleAlbum]
StringAlign=LeftCenter
StringCase=None
StringStyle=Normal
FontColor=#ColorCode#
FontFace=#TypeFace#
FontSize=(15*#SuiteScale#)
AntiAlias=1
ClipString=1
DynamicVariables=1

[SpotifyStylePosition]
StringAlign=LeftCenter
StringCase=None
StringStyle=Normal
FontColor=#ColorCode#
FontFace=#TypeFace#
FontSize=(15*#SuiteScale#)
AntiAlias=1
DynamicVariables=1

; ==================================================
; WEATHER SKINS

[WeatherImageIcon]
ImagePath=#@#Images\Weather\
ImageTint=#ColorCode#
AntiAlias=1
DynamicVariables=1

[WeatherStyleRetreieve]
StringAlign=CenterCenter
FontFace=#TypeFace#
FontColor=#ColorCode#
FontSize=(30*#SuiteScale#)
AntiAlias=1
DynamicVariables=1

[WeatherStyleTop]
StringAlign=LeftCenter
FontFace=#TypeFace#
FontColor=#ColorCode#
FontSize=(18*#SuiteScale#)
AntiAlias=1
DynamicVariables=1

[WeatherStyleCurrent]
StringAlign=LeftCenter
FontFace=#TypeFace#
FontColor=#ColorCode#
FontSize=(50*#SuiteScale#)
AntiAlias=1
DynamicVariables=1

[WeatherStyleCurrentText]
StringAlign=LeftCenter
FontFace=#TypeFace#
FontColor=#ColorCode#
FontSize=(20*#SuiteScale#)
ClipString=2
ClipStringW=(200*#SuiteScale#)
AntiAlias=1
DynamicVariables=1

[WeatherStyleFeels]
StringAlign=LeftCenter
FontFace=#TypeFace#
FontColor=#c8c8c8
FontSize=(20*#SuiteScale#)
AntiAlias=1
DynamicVariables=1

[WeatherStyleSunMoon]
StringAlign=LeftCenter
FontFace=#TypeFace#
FontColor=#ColorCode#
FontSize=(18*#SuiteScale#)
AntiAlias=1
DynamicVariables=1

[WeatherStyleLocation]
StringAlign=CenterCenter
StringCase=Upper
FontFace=#TypeFace#
FontColor=#ColorCode#
FontSize=(13*#SuiteScale#)
AntiAlias=1
DynamicVariables=1

[WeatherStyleLine]
Shape=Line 0,0,(500*#SuiteScale#),0 | Stroke Color #ColorCode# | StrokeWidth 2
AntiAlias=1
DynamicVariables=1

[WeatherStyleDay]
StringAlign=LeftCenter
StringCase=Proper
FontFace=#TypeFace#
FontColor=#ColorCode#
FontSize=(20*#SuiteScale#)
ClipString=1
AntiAlias=1
DynamicVariables=1

[WeatherHighTemp]
StringAlign=RightCenter
FontFace=#TypeFace#
FontColor=255,128,128
FontSize=(20*#SuiteScale#)
AntiAlias=1
DynamicVariables=1

[WeatherLowTemp]
StringAlign=RightCenter
FontFace=#TypeFace#
FontColor=128,255,255
FontSize=(20*#SuiteScale#)
AntiAlias=1
DynamicVariables=1

; ==================================================
; WEATHER SLIM SKINS

[WeatherSlimImageIcon]
ImagePath=#@#Images\Weather\
ImageTint=#ColorCode#
AntiAlias=1
DynamicVariables=1

[WeatherSlimStyleRetreieve]
StringAlign=CenterCenter
FontFace=#TypeFace#
FontColor=#ColorCode#
FontSize=(30*#SuiteScale#)
AntiAlias=1
DynamicVariables=1

[WeatherSlimStyleTop]
StringAlign=LeftCenter
FontFace=#TypeFace#
FontColor=#ColorCode#
FontSize=(18*#SuiteScale#)
AntiAlias=1
DynamicVariables=1

[WeatherSlimStyleCurrent]
StringAlign=LeftCenter
FontFace=#TypeFace#
FontColor=#ColorCode#
FontSize=(50*#SuiteScale#)
AntiAlias=1
DynamicVariables=1

[WeatherSlimStyleCurrentText]
StringAlign=LeftCenter
FontFace=#TypeFace#
FontColor=#ColorCode#
FontSize=(20*#SuiteScale#)
ClipString=2
ClipStringW=200
AntiAlias=1
DynamicVariables=1

[WeatherSlimStyleFeels]
StringAlign=LeftCenter
FontFace=#TypeFace#
FontColor=#ColorCode#,128
FontSize=(20*#SuiteScale#)
AntiAlias=1
DynamicVariables=1

[WeatherSlimStyleSunMoon]
StringAlign=LeftCenter
FontFace=#TypeFace#
FontColor=#ColorCode#
FontSize=(18*#SuiteScale#)
AntiAlias=1
DynamicVariables=1

; ==================================================
; WEATHER SLIM EXTRA SKINS

[WeatherSlimExtraImageIcon]
ImagePath=#@#Images\Weather\
ImageTint=#ColorCode#
AntiAlias=1
DynamicVariables=1

[WeatherSlimExtraStyleRetreieve]
StringAlign=CenterCenter
FontFace=#TypeFace#
FontColor=#ColorCode#
FontSize=(30*#SuiteScale#)
AntiAlias=1
DynamicVariables=1

[WeatherSlimExtraStyleTop]
StringAlign=LeftCenter
FontFace=#TypeFace#
FontColor=#ColorCode#
FontSize=(18*#SuiteScale#)
AntiAlias=1
DynamicVariables=1

[WeatherSlimExtraStyleCurrent]
StringAlign=LeftCenter
FontFace=#TypeFace#
FontColor=#ColorCode#
FontSize=(50*#SuiteScale#)
AntiAlias=1
DynamicVariables=1

[WeatherSlimExtraStyleCurrentText]
StringAlign=LeftCenter
FontFace=#TypeFace#
FontColor=#ColorCode#
FontSize=(20*#SuiteScale#)
ClipString=2
ClipStringW=200
AntiAlias=1
DynamicVariables=1

[WeatherSlimExtraStyleFeels]
StringAlign=LeftCenter
FontFace=#TypeFace#
FontColor=#ColorCode#,128
FontSize=(20*#SuiteScale#)
AntiAlias=1
DynamicVariables=1
