; Do NOT change this file unless you are sure you know what you are doing !!!
; ========================================================================

[Variables]



Latitude=-34.668056
Longitude=20.231111

APIKey=71f92ea9dd2f4790b92ea9dd2f779061

URL=https://api.weather.com/v3/aggcommon/v3-wx-observations-current;v3-location-point?format=json&geocode=#Latitude#,#Longitude#&units=#Units#&language=#Language#&apiKey=#APIKey#


Language=en-US

Units=e

SizeValue=0.18

HiddenText=1


FontFace=CyberpunkWaifus
FontFace2=CyberpunkWaifus
FontFace3=CyberpunkWaifus


FontColor=255,255,255,255
FontColor2=255,255,255,255
FontColor3=191,216,242,255
FontEffectColor=0,0,0,50
FontEffectColor2=0,0,0,200
