[SpotifyIcon]
ImagePath=#@#Images\Spotify\
ImageTint=#ColorCode#
AntiAlias=1
DynamicVariables=1

[SpotifyPosition]
ImageName=#@#Images\Spotify\Position.png
ImageTint=#ColorCode#
AntiAlias=1
DynamicVariables=1
UpdateDivider=1

[SpotifyPlayback]
Shape=Rectangle 0,0,([MeasureProgressTime]*#SuiteScale#),(9*#SuiteScale#),(5*#SuiteScale#) | Fill Color #ColorCode# | StrokeWidth 0
AntiAlias=1
DynamicVariables=1
UpdateDivider=1
