Remove-Item -Recurse -Force -ErrorAction SilentlyContinue "$env:USERPROFILE\3D Objects"
Remove-Item -Recurse -Force -ErrorAction SilentlyContinue "$env:USERPROFILE\Contacts"
Remove-Item -Recurse -Force -ErrorAction SilentlyContinue "$env:USERPROFILE\Favorites"
Remove-Item -Recurse -Force -ErrorAction SilentlyContinue "$env:USERPROFILE\iCloudDrive"
Remove-Item -Recurse -Force -ErrorAction SilentlyContinue "$env:USERPROFILE\MEGABASTERD_UPLOAD_LOGS"
Remove-Item -Recurse -Force -ErrorAction SilentlyContinue "$env:USERPROFILE\Recorded Calls"
Remove-Item -Recurse -Force -ErrorAction SilentlyContinue "$env:USERPROFILE\Searches"
Remove-Item -Recurse -Force -ErrorAction SilentlyContinue "$env:USERPROFILE\Documents\Custom Office Templates"
Remove-Item -Recurse -Force -ErrorAction SilentlyContinue "$env:USERPROFILE\Pictures\Camera Roll"
Remove-Item -Recurse -Force -ErrorAction SilentlyContinue "$env:USERPROFILE\Pictures\iCloud Photos"
Remove-Item -Recurse -Force -ErrorAction SilentlyContinue "$env:USERPROFILE\Pictures\Saved Pictures"
Remove-Item -Force -ErrorAction SilentlyContinue "$env:USERPROFILE\Documents\Default.rdp"
